server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.vodafone.services.sms
  api-docs: 
      path: /api-docs
      
spring:
  zipkin:
    base-url: http://localhost:9411/    
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Passw0rd@!
    username: sms
    url: jdbc:mysql://172.30.1.149:3306/dlr
    
smsc:
  connections:
    host: 10.231.101.102
    sourcePhoneNo: MarketHub
    port: '8313'
    connectionType: TRANSCEIVER
  kannel:
    config:
      smsFrom: MarketHub
      dlrMask: '31'
      smsPassword: hybrid
      smsBoxSmscId: MHUB_SMSC
      priorityLevel: '3'
      smsBoxUrl: http://172.30.1.149:13013/markethub
      smsUserName: hybrid
  jms:
    jackson:
      messageconverter:
        typeIdPropertyName: _type
  credentials:
    username: MarketHUB
    password: SDFG@369
  scheduling:
    cron:
      expression:
        timezone: Africa/Lagos
        smsqueue:
          pending: 0/30 0/1 * 1/1 * ?
  jmslistener:
    containerfactory:
      name: smsContainerFactory
      concurrency: 3-10
  smpp:
    session:
      timeoutMillis: '6000'
    serviceType: CMT
  persistence:
    query:
      limit: '15'
  jmstemplate:
    message:
      destinationName: smsBoxQueue
  sms:
    dispatch:
      retry:
        maxlimit: '7'
#server:
#  port: '9090'